services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=spring_demo'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432
    volumes:
      - ../pgdata:/tmp/pgdata
